from .benchmark_factors import BENCHMARK_REGISTRY, BenchmarkFactorRegistry
from .blocks import (
    Block,
    BlockExecutor,
    CombineBlock,
    CustomRequest,
    DataBlock,
    FactorHypothesis,
    FilterBlock,
    OperatorRegistry,
    ProgrammingPlan,
    RelationalBlock,
    TransformBlock,
    block_to_factor_node,
    combine,
    data,
    factor_node_to_block,
    filter_block,
    relational,
    transform,
)
from .datahub import DataHub, DataProvider, DataQualityReport, LocalCSVProvider
from .decay_monitor import DecayCheckResult, DecayMonitorSummary, FactorDecayMonitor
from .delivery_screener import DeliveryScreener, ScreeningResult, ScreeningSummary
from .evolution import EvolutionConfig, FactorEvolutionLoop, Trajectory, TrajectoryStep
from .factor_namer import FactorNamer, FactorVersionManager
from .factor_report import FactorDeliveryReport, FactorDeliveryReportGenerator
from .hypothesis import FactorHypothesisGenerator, HypothesisCandidate, HypothesisRequest
from .llm_supervisor import LLMSupervisor
from .models import (
    AgentRole,
    ConstraintScorecard,
    FactorDependency,
    FactorDirection,
    FactorEvaluationReport,
    FactorExecutionSpec,
    FactorExperience,
    FactorLabelSpec,
    FactorLibraryEntry,
    FactorMemorySnapshot,
    FactorNode,
    FactorPreprocessConfig,
    FactorResearchPlan,
    FactorResearchTask,
    FactorScorecard,
    FactorSpec,
    FactorStatus,
    FactorUniverseSpec,
    FactorValidationResult,
    ResearchStage,
    RoleAssignment,
    SandboxPolicy,
    SandboxValidationResult,
)
from .multi_agent import (
    BaseAgent,
    FactorMultiAgentOrchestrator,
    LLMClient,
    MessageBus,
    MultiAgentConfig,
    P1Architect,
    P2BlockAssembler,
    P3CustomCoder,
    R1HypothesisGenerator,
    R2HypothesisReviewer,
    T1Backtester,
    T2Validator,
)
from .pipeline import FactorDiscoveryOrchestrator, build_default_factor_pipeline, evaluate_factor_metrics
from .real_return import RealReturnEvaluator, RealReturnReport, compare_to_ic
from .runtime import FactorExperienceMemory, PersistentFactorStore, SafeFactorExecutor
from .sample_split import SampleSplitter, SplitResult

__all__ = [
    "AgentRole",
    "ConstraintScorecard",
    "FactorDependency",
    "FactorDirection",
    "FactorEvaluationReport",
    "FactorExecutionSpec",
    "FactorExperience",
    "FactorExperienceMemory",
    "FactorLabelSpec",
    "FactorLibraryEntry",
    "FactorMemorySnapshot",
    "FactorNode",
    "FactorPreprocessConfig",
    "FactorResearchPlan",
    "FactorResearchTask",
    "FactorScorecard",
    "FactorSpec",
    "FactorStatus",
    "FactorUniverseSpec",
    "FactorValidationResult",
    "PersistentFactorStore",
    "ResearchStage",
    "RoleAssignment",
    "SafeFactorExecutor",
    "SandboxPolicy",
    "SandboxValidationResult",
    "FactorDiscoveryOrchestrator",
    "build_default_factor_pipeline",
    "evaluate_factor_metrics",
    # 新增模块
    "FactorHypothesisGenerator",
    "HypothesisCandidate",
    "HypothesisRequest",
    "FactorEvolutionLoop",
    "EvolutionConfig",
    "Trajectory",
    "TrajectoryStep",
    "DataHub",
    "DataQualityReport",
    "DataProvider",
    "LocalCSVProvider",
    # 因子交付
    "FactorDeliveryReport",
    "FactorDeliveryReportGenerator",
    # 衰减监控
    "FactorDecayMonitor",
    "DecayCheckResult",
    "DecayMonitorSummary",
    # 交付筛选
    "DeliveryScreener",
    "ScreeningResult",
    "ScreeningSummary",
    # 积木体系
    "Block",
    "DataBlock",
    "TransformBlock",
    "CombineBlock",
    "RelationalBlock",
    "FilterBlock",
    "BlockExecutor",
    "OperatorRegistry",
    "FactorHypothesis",
    "ProgrammingPlan",
    "CustomRequest",
    "data",
    "transform",
    "combine",
    "relational",
    "filter_block",
    "factor_node_to_block",
    "block_to_factor_node",
    # 样本外拆分
    "SampleSplitter",
    "SplitResult",
    # 多 Agent 协作
    "FactorMultiAgentOrchestrator",
    "MultiAgentConfig",
    "LLMClient",
    "MessageBus",
    "BaseAgent",
    "R1HypothesisGenerator",
    "R2HypothesisReviewer",
    "P1Architect",
    "P2BlockAssembler",
    "P3CustomCoder",
    "T1Backtester",
    "T2Validator",
    # LLM Supervisor
    "LLMSupervisor",
    # 真实收益评估
    "RealReturnEvaluator",
    "RealReturnReport",
    "compare_to_ic",
    # 基准因子注册表
    "BenchmarkFactorRegistry",
    "BENCHMARK_REGISTRY",
    # 因子命名与版本管理
    "FactorNamer",
    "FactorVersionManager",
]
